#!/usr/bin/env python3
"""Independent algebra and exact-endpoint replay for the actual initial jets."""
from pathlib import Path
from fractions import Fraction as F
import json
import sympy as s

# Logistic composition derivatives, independently generated by a total derivative.
p,z1,z2,z3,z4,z5=s.symbols("p z1 z2 z3 z4 z5")
h=p*(1-p)
zs=[z1,z2,z3,z4,z5]
def D(expr):
    return s.expand(s.diff(expr,p)*h*z1+
                    sum(s.diff(expr,zs[j])*zs[j+1] for j in range(4)))
actual=[p]
for j in range(4):
    actual.append(D(actual[-1]))
expected=[
 p,h*z1,h*((1-2*p)*z1*z1+z2),
 h*((1-6*p+6*p*p)*z1**3+3*(1-2*p)*z1*z2+z3),
 h*((1-14*p+36*p*p-24*p**3)*z1**4+
    6*(1-6*p+6*p*p)*z1*z1*z2+
    3*(1-2*p)*z2*z2+4*(1-2*p)*z1*z3+z4)]
assert all(s.expand(a-b)==0 for a,b in zip(actual,expected))

# Independent g=r² f(r²/a²) derivatives through four.
r,a=s.symbols("r a",positive=True)
x=s.symbols("x")
f=s.Function("f")
g=r*r*f(r*r/(a*a))
d=[s.diff(f(x),x,j).subs(x,r*r/(a*a)) for j in range(5)]
gj=[
 r*r*d[0],2*r*d[0]+2*r**3/a**2*d[1],
 2*d[0]+10*r*r/a**2*d[1]+4*r**4/a**4*d[2],
 24*r/a**2*d[1]+36*r**3/a**4*d[2]+8*r**5/a**6*d[3],
 24/a**2*d[1]+156*r*r/a**4*d[2]+112*r**4/a**6*d[3]+16*r**6/a**8*d[4]]
assert all(s.simplify(s.diff(g,r,j)-gj[j])==0 for j in range(5))

# Pressure source simplification at the maximum and phase multiplication.
m,k,C=s.symbols("m k C",real=True)
source=2*C*(m*m/r**2-k*k-s.I*k/r)
assert s.simplify(s.expand(-s.I*k*r*source/2).as_real_imag()[0]+k*k*C)==0
K,co,si,Pr,Pi=s.symbols("K co si Pr Pi",real=True)
product=s.expand((co-s.I*si)*(K+s.I*k)*(Pr+s.I*Pi)).as_real_imag()[0]
assert s.expand(product-((K*co+k*si)*Pr-(k*co-K*si)*Pi))==0

# Radial critical branch speed and the envelope correction.
A,c,nu,T,g2,g3=s.symbols("A c nu T g2 g3",real=True)
Gtr=A*(-c*r*g2+nu*(g3-g2/r))-T/r
speed=-Gtr/(A*g2)
explicit=c*r-nu*(g3/g2-1/r)+T/(r*A*g2)
assert s.simplify(speed-explicit)==0
assert s.simplify(2*Gtr*speed+A*g2*speed**2+Gtr**2/(A*g2))==0

data=json.loads((Path(__file__).resolve().parent/
                 "fixed-circle-acceleration-certificate.json").read_text())
def endpoint(key,side):
    z=data[key]["exact"][side]
    return (-1 if z["sign"] else 1)*F(int(z["mantissa"]))*F(2)**z["exponent"]
assert data["status"]=="PASS"
assert endpoint("mean_transport_diffusion_coefficient","upper")<0
assert endpoint("seed_coefficient_upper_expression","upper")<0
assert endpoint("viscous_torque_factor","upper")<0
assert endpoint("Gtt_upper_expression","upper")<-250000
if "moving_radial_maximum_Gtt_upper_expression" in data:
    assert endpoint("moving_radial_maximum_Gtt_upper_expression","upper")<-240000
    assert endpoint("Gt_interval","lower")>85
    assert endpoint("Gt_interval","upper")<186
    assert endpoint("initial_radial_maximum_speed","lower")>F(1,5)
print("PASS: logistic/g jets through order four, full source and phase signs, "
      "moving radial branch formulas, and saved exact initial-jet inequalities.")
