"""rlib -- refuter's own instrument for the hk2 majorant.  Written from the statement of
hk2 PROOF.md sec 3-4 (the reduction (3.1) and the bounds (4.3)-(4.4)); NO code imported from hk2.
Derivatives of the datum are generated by sympy (hk2 hand-codes a chain rule), and the
strained field eta_lam(r,z) = eta_0(r/lam, lam^2 z) is differentiated by sympy on the composed
expression.  Units rho0 = M = 1.

Datum (D-B) as read from the record (dcommon.py parameters restated in hk2 sec 2):
   omega = - tanh(sin phi / sin delta) tanh(cos phi / w) Theta(rho),
   Theta = (1/2)[tanh((rho-1)/w0) - tanh((rho-R)/w1)],  w0 = 0.25, w1 = 0.1 R,
   eta = omega / r.
"""
import math, functools
import numpy as np
import sympy as sp

C_K     = 3.0/(8*math.pi**2)
C_GRADK = 3.0/(2*math.pi**2)
THETA_MAX = 4.0*(1.0-math.sqrt(2.0/3.0))

@functools.lru_cache(maxsize=None)
def _build(delta_deg, w, L, lam, w0=0.25, w1frac=0.10):
    r, z = sp.symbols('r z', positive=True)
    R = sp.exp(L)
    sd = sp.sin(sp.rad(delta_deg))
    rr = r/lam; zz = lam**2*z                       # pull-back to the label
    rho = sp.sqrt(rr**2 + zz**2)
    sphi = rr/rho; cphi = zz/rho
    Theta = sp.Rational(1,2)*(sp.tanh((rho-1)/w0) - sp.tanh((rho-R)/(w1frac*R)))
    omega = -sp.tanh(sphi/sd)*sp.tanh(cphi/w)*Theta
    eta = omega/rr                                  # eta_0 evaluated at the pulled-back point
    er = sp.diff(eta, r); ez = sp.diff(eta, z)
    err = sp.diff(er, r); erz = sp.diff(er, z); ezz = sp.diff(ez, z)
    fn = {}
    fn['grad2'] = sp.lambdify((r, z), (er, ez), 'numpy', cse=True)
    fn['all']   = sp.lambdify((r, z), (eta, er, ez, err, erz, ezz), 'numpy', cse=True)
    return fn

class Field:
    """eta_lam and its first two derivatives; lam = 1 is the datum itself."""
    def __init__(self, delta_deg=7.5, w=0.20, L=10.0, lam=1.0):
        self.fn = _build(float(delta_deg), float(w), float(L), float(lam))
        self.lam = float(lam); self.R = math.exp(L); self.L = L
    def all(self, r, z):
        r = np.asarray(r, float); z = np.asarray(z, float)
        return [np.asarray(v, float) for v in self.fn['all'](r, z)]
    def grad(self, r, z):
        er, ez = self.fn['grad2'](np.asarray(r, float), np.asarray(z, float))
        return np.sqrt(er*er + ez*ez)
    def hessF(self, r, z):
        _, er, ez, err, erz, ezz = self.all(r, z)
        return np.sqrt(err**2 + 2*erz**2 + ezz**2 + 3*(er/r)**2)

class PushedGradient:
    """the Lemma-7.2-licensed majorant of |grad eta(.,t)|: factor * |grad eta_0|(T_lam^{-1} x'),
    i.e. the isotropic growth e^{int Gamma} applied to the initial gradient at the label point
    (no anisotropic T^{-T}; no diffusion)."""
    def __init__(self, base, lam, factor):
        self.b = base; self.lam = float(lam); self.f = float(factor)
    def grad(self, r, z):
        return self.f*self.b.grad(r/self.lam, self.lam**2*z)

# ------------------------------------------------------------------- geometry
def strain_point(phi0_deg, lam, f=0.0):
    phi0 = math.radians(phi0_deg); rho = 1.0+f
    r0, z0 = rho*math.sin(phi0), rho*math.cos(phi0)
    return lam*r0, z0/lam**2

def dist_cone(r, z, ang):
    n = (math.cos(ang), -math.sin(ang))
    return abs(r*n[0] + z*n[1])

def distances(r, z, lam, delta_deg=7.5):
    cone = math.atan(lam**3*math.tan(math.radians(delta_deg)))
    return dict(d_eq=abs(z), d_tap=dist_cone(r, z, cone), cone_deg=math.degrees(cone))

# ------------------------------------------------------------------- the kernel majorant
@functools.lru_cache(maxsize=None)
def _gl(n):
    return np.polynomial.legendre.leggauss(n)
def _gauss(n, a, b):
    x, w = _gl(n); return 0.5*(b-a)*x + 0.5*(b+a), 0.5*(b-a)*w

def Lambda(gradfun, r, z, d, smax, ns=300, nT=120, nc=120):
    """Lambda_p = int_{|w|>d} |w|^{-p} |grad eta|(x-w) dw, p=4,5, in x-centred 5D spherical
    coordinates: w = s(sin T nhat, cos T), nhat in S^3 at angle chi to yhat.
    dw = s^4 ds sin^3 T dT 4pi sin^2 chi dchi."""
    u, wu = _gauss(ns, math.log(d), math.log(smax)); s = np.exp(u); ws = wu*s
    T, wT = _gauss(nT, 0.0, math.pi); X, wX = _gauss(nc, 0.0, math.pi)
    sT = np.sin(T)[:,None]; cT = np.cos(T)[:,None]; cX = np.cos(X)[None,:]
    W = (wT*np.sin(T)**3)[:,None]*(wX*4*math.pi*np.sin(X)**2)[None,:]
    A = np.empty(ns)
    for i, si in enumerate(s):
        rp = np.sqrt(np.maximum(r*r + (si*sT)**2 - 2*r*si*sT*cX, 1e-300))
        zp = (z - si*cT)*np.ones_like(cX)
        A[i] = np.sum(W*gradfun(rp, zp))
    return float(np.sum(ws*A)), float(np.sum(ws*A/s))     # Lambda_4, Lambda_5

def ball_sups(F, r0, z0, d, n=241):
    g = np.linspace(-d, d, n)
    RR, ZZ = np.meshgrid(r0+g, z0+g, indexing='ij')
    m = (RR-r0)**2 + (ZZ-z0)**2 <= d*d
    RR = np.where(m, RR, r0); ZZ = np.where(m, ZZ, z0); RR = np.maximum(RR, 1e-6)
    th = np.linspace(0, 2*math.pi, 4001)
    rb = np.maximum(r0+d*np.cos(th), 1e-6); zb = z0+d*np.sin(th)
    return float(np.max(F.grad(RR, ZZ))), float(np.max(F.hessF(RR, ZZ))), float(np.max(F.grad(rb, zb)))

def assemble(sg, sh, sb, d, L4, L5, r, eta, eta_r, eta_z):
    """hk2 (4.3), (4.4), (3.1) -- re-typed from the statement."""
    ga = d*sg + C_K*L4
    Ha = d*sh + sb + C_GRADK*L5
    q  = ga + abs(eta); qr = Ha + abs(eta_r); qz = Ha + abs(eta_z)
    S55 = 2*ga + r*Ha
    Huz = max(q, q + r*qr + r*qz, r*qz + S55)
    return dict(grad_a=ga, hess_a=Ha, hess_uz=Huz, K2=r*Ha + 2*ga + Huz)

def bound_at(F, r, z, dmax, gradfun=None, nd=8, ns=300, nT=120, nc=120, sup_field=None,
             local_factor=1.0, dgrid=None):
    """optimise the majorant over the ball radius d in (0, dmax].  gradfun: the TV density
    used inside Lambda (default F.grad).  sup_field: the field whose ball sups are used
    (default F).  local_factor multiplies |grad eta| at the point."""
    gradfun = gradfun or F.grad; SF = sup_field or F
    e, er, ez, *_ = F.all(np.array([r]), np.array([z]))
    e, er, ez = float(e[0]), float(er[0])*local_factor, float(ez[0])*local_factor
    best = None
    for d in (dgrid if dgrid is not None else np.linspace(0.05*dmax, dmax, nd)):
        L4, L5 = Lambda(gradfun, r, z, d, 3*F.R, ns, nT, nc)
        sg, sh, sb = ball_sups(SF, r, z, d)
        A = assemble(sg, sh, sb, d, L4, L5, r, e, er, ez)
        A.update(d=float(d), L4=L4, L5=L5, sup_grad=sg, sup_hess=sh, sup_grad_bdry=sb)
        if best is None or A['K2'] < best['K2']: best = A
    best.update(r=r, z=z, eta=e, eta_r=er, eta_z=ez)
    return best

class PushedField:
    """Lemma-7.2-licensed majorants of the field at time t, from the datum at the LABEL point
    T_lam^{-1} x:  |grad eta(x,t)| <= fg * |grad eta_0|(T^{-1}x),  ||Hess eta(x,t)||_F <= fh *
    ||Hess eta_0||_F(T^{-1}x)  (fg = e^{int Gamma}, fh = e^{2 int Gamma}; feedback term dropped;
    diffusion dropped).  eta itself is the material value (max principle / material identity)."""
    def __init__(self, base, lam, fg, fh):
        self.b = base; self.lam = float(lam); self.fg = float(fg); self.fh = float(fh)
        self.R = base.R
    def _pull(self, r, z):
        return np.asarray(r, float)/self.lam, self.lam**2*np.asarray(z, float)
    def grad(self, r, z):  return self.fg*self.b.grad(*self._pull(r, z))
    def hessF(self, r, z): return self.fh*self.b.hessF(*self._pull(r, z))
    def all(self, r, z):
        e, er, ez, err, erz, ezz = self.b.all(*self._pull(r, z))
        return [e, self.fg*er, self.fg*ez, self.fh*err, self.fh*erz, self.fh*ezz]
