#!/usr/bin/env python3
"""s3_ode.py -- the self-consistent Lagrangian strain ODE and its closed form.

MODEL (Proposition 4).  sigma = s/L in [0,1] labels the material shell (s = log(rho/rho_0)),
theta = M L t the rescaled time, F(sigma,theta) = int_0^t a ds along the trajectory of that shell,
lam = e^F its accumulated strain factor.  Lemma 1 (P_h(lam) = lam for the plateau) plus
"the strain at shell sigma is generated by the shells outside it" give the closed system

        d_theta F(sigma,theta) = kappa * H(sigma,theta),   H(sigma,theta) = int_sigma^1 e^{F} dsigma'.

Then d_theta d_sigma H = -e^F d_theta F = kappa H d_sigma H = d_sigma(kappa H^2/2), and H(1,.) = 0
forces the integration constant to vanish, so

        d_theta H = (kappa/2) H^2,  H(sigma,0) = 1-sigma
   =>   H = (1-sigma) / (1 - (1-sigma) kappa theta / 2),
        F = -2 log(1 - (1-sigma) kappa theta / 2),
        lam(sigma,theta) = (1 - (1-sigma) kappa theta/2)^{-2}.

Doubling-to-(3/2) at the innermost shell sigma=0:  lam = 3/2  <=>  kappa theta = 2(1 - sqrt(2/3)).
Model blow-up (lam = infinity) at kappa theta = 2.

Checks: (a) closed form satisfies the integro-ODE; (b) direct method-of-lines solve reproduces it;
(c) frozen-strain comparison; (d) the general-profile version with P_h from s1.
"""
import numpy as np, json
from scipy.integrate import solve_ivp

OUT = {}
kappa = 0.5

# ---------------- (a) closed form vs the integro-ODE, verified symbolically-in-numbers
def F_closed(sig, th, kap=kappa):  return -2*np.log(1 - (1-sig)*kap*th/2)
def H_closed(sig, th, kap=kappa):  return (1-sig)/(1 - (1-sig)*kap*th/2)

sig = np.linspace(0,1,20001)
res = []
for th in [0.0, 0.2, 0.5, 0.734, 1.0, 2.0]:
    F = F_closed(sig, th); H = H_closed(sig, th)
    # H must equal int_sigma^1 e^F
    eF = np.exp(F)
    Hnum = np.concatenate([np.array([np.trapz(eF, sig)]),
                           np.trapz(eF[None,:], sig)*np.ones(0)]) if False else None
    # cumulative from the right
    cum = np.zeros_like(sig)
    cum[:-1] = np.cumsum(((eF[1:]+eF[:-1])/2)*np.diff(sig)[::1][::-1][::-1])  # placeholder
    # do it properly
    d = np.diff(sig); trap = (eF[1:]+eF[:-1])/2*d
    tail = np.concatenate([np.cumsum(trap[::-1])[::-1], [0.0]])
    res.append((th, float(np.max(np.abs(tail - H)))))
OUT['closed_form_H_equals_tail_integral_maxabs'] = res

# ---------------- (b) direct method-of-lines solve of d_theta F = kappa int_sigma^1 e^F
N = 4001
sg = np.linspace(0,1,N)
def rhs(t, F):
    eF = np.exp(F)
    d = np.diff(sg); trap = (eF[1:]+eF[:-1])/2*d
    tail = np.concatenate([np.cumsum(trap[::-1])[::-1], [0.0]])
    return kappa*tail
sol = solve_ivp(rhs, [0, 1.8], np.zeros(N), rtol=1e-11, atol=1e-13, dense_output=True)
chk = []
for th in [0.2, 0.5, 0.734011, 1.0, 1.5]:
    Fn = sol.sol(th); Fc = F_closed(sg, th)
    chk.append((th, float(np.max(np.abs(Fn-Fc))), float(Fn[0]), float(Fc[0])))
OUT['mol_vs_closed'] = chk

# ---------------- (c) the two constants
from scipy.optimize import brentq
th32 = brentq(lambda th: F_closed(0.0, th) - np.log(1.5), 1e-9, 3.9)
th2  = brentq(lambda th: F_closed(0.0, th) - np.log(2.0), 1e-9, 3.9)
OUT['theta_32_numeric'] = th32
OUT['theta_32_exact']   = 4*(1-np.sqrt(2/3))
OUT['theta_2_exact']    = 4*(1-np.sqrt(0.5))
OUT['theta_32_frozen']  = 2*np.log(1.5)      # kappa=1/2, strain held at its t=0 value
OUT['theta_blowup']     = 2/kappa
# c2 in  M T_d <= c2 / log Re_E , using log Re_E = 2L - 0.7032 <= 2L
OUT['c2_accel']  = 2*OUT['theta_32_exact']
OUT['c2_frozen'] = 2*OUT['theta_32_frozen']
OUT['c2_frozen_check_4log32'] = 4*np.log(1.5)
OUT['c2_accel_check_8'] = 8*(1-np.sqrt(2/3))

# ---------------- (d) diagnostics used to compare with the campaign's viscous runs
th = OUT['theta_32_exact']
OUT['H0_at_theta32'] = H_closed(0.0, th)                    # mean per-octave enhancement
OUT['T_a_star']      = th*kappa*H_closed(0.0, th)           # T * a(T)  in the same units
OUT['int_a']         = F_closed(0.0, th)                    # = log(3/2)
OUT['overhead_T_astar_over_int_a'] = OUT['T_a_star']/OUT['int_a']

# viscous-numerics cross-check: their datum has kappa_meas ~ 0.411 at N=6
for kap_m in [0.400, 0.411, 0.415, 0.437]:
    thm = 2*(1-np.sqrt(2/3))/kap_m
    OUT.setdefault('Qprime_prediction', []).append(
        (kap_m, thm, np.log(1.5)/kap_m, OUT['overhead_T_astar_over_int_a']))

print(json.dumps(OUT, indent=1, default=str))
json.dump(OUT, open('s3_results.json','w'), indent=1, default=str)
