import Cores
open ForcedRoute

#print axioms Criticality.theta_nonneg
#print axioms Criticality.theta_lt_one_iff
#print axioms Criticality.theta_lt_one
#print axioms Criticality.theta_mem_Ico
#print axioms Criticality.theta_two
#print axioms Criticality.theta_one
#print axioms Criticality.sobolev_index_interpolation
#print axioms Criticality.one_sub_theta
#print axioms Criticality.two_div_one_sub_theta
#print axioms Criticality.scalingMap_surjective
#print axioms Criticality.norm_rescale
#print axioms Criticality.iSup_norm_rescale
#print axioms Criticality.bddAbove_range_norm_rescale
#print axioms Criticality.iSup_norm_rescale_of_bddAbove
#print axioms Criticality.supNorm_scaling_invariant_iff

#print axioms CircleMeasure.lipschitzWith_coord
#print axioms CircleMeasure.hausdorffMeasure_image_coord_le
#print axioms CircleMeasure.Icc_subset_coord_image_circleAt
#print axioms CircleMeasure.hausdorffMeasure_Icc
#print axioms CircleMeasure.hausdorffMeasure_circleAt_pos
#print axioms CircleMeasure.hausdorffMeasure_circle_pos
#print axioms CircleMeasure.exists_cos_sin
#print axioms CircleMeasure.exists_rot_eq
#print axioms CircleMeasure.circleAt_subset_of_rotInvariant
#print axioms CircleMeasure.hausdorffMeasure_pos_of_rotInvariant

#print axioms Ceiling.rpow_lt_rpow_exponent_iff
#print axioms Ceiling.damping_below_growth_iff
#print axioms Ceiling.mul_lt_half_iff
#print axioms Ceiling.isGreatest_ceiling
#print axioms Ceiling.csSup_ceiling
#print axioms Ceiling.ceiling_le_half
#print axioms Ceiling.lt_half_of_admissible
#print axioms Ceiling.lt_half_of_damping_below_growth

#print axioms StrainedCore.trace_Lmat
#print axioms StrainedCore.Lmat_sq_zz
#print axioms StrainedCore.trace_Lmat_sq
#print axioms StrainedCore.affine_pressure_zz
#print axioms StrainedCore.affine_ne_core
#print axioms StrainedCore.Cutoff.cont0
#print axioms StrainedCore.Cutoff.cont1
#print axioms StrainedCore.Cutoff.int1
#print axioms StrainedCore.Cutoff.int2
#print axioms StrainedCore.Cutoff.int3
#print axioms StrainedCore.Cutoff.int4
#print axioms StrainedCore.Cutoff.I_def
#print axioms StrainedCore.Cutoff.moment_one
#print axioms StrainedCore.Cutoff.moment_two
#print axioms StrainedCore.Cutoff.moment_three
#print axioms StrainedCore.Cutoff.lincomb
#print axioms StrainedCore.Cutoff.strain_radial
#print axioms StrainedCore.Cutoff.swirl_radial
#print axioms StrainedCore.Cutoff.core_pressure_zz
#print axioms StrainedCore.Cutoff.core_pressure_transverse
#print axioms StrainedCore.Cutoff.core_pressure_zz_of_pure_rotation
#print axioms StrainedCore.Cutoff.radial_moment
#print axioms StrainedCore.angular_average
#print axioms StrainedCore.rotating_core_coefficient
#print axioms StrainedCore.ratio_second_derivative_algebraic
#print axioms StrainedCore.ratio_second_derivative

#print axioms Receiver.stageTime_pos
#print axioms Receiver.gain_pos
#print axioms Receiver.one_lt_one_add_gain
#print axioms Receiver.stageTime_mono
#print axioms Receiver.gain_mono
#print axioms Receiver.gain_stageTime_mono
#print axioms Receiver.contraction_sq_mem_Ioo
#print axioms Receiver.contraction_sq_mul
#print axioms Receiver.strict_Re_gain_iff
#print axioms Receiver.Re_ratio_gt_one
#print axioms Receiver.vel_ratio_gt_one
#print axioms Receiver.energy_ratio_pos
#print axioms Receiver.energy_ratio_lt_one
#print axioms Receiver.scale_match_Re
#print axioms Receiver.scale_match_energy
#print axioms Receiver.vel_ratio_sq
#print axioms Receiver.scale_match_energy'
#print axioms Receiver.quarter_exponents
#print axioms Receiver.quarter_Re_ratio
#print axioms Receiver.quarter_vel_ratio
#print axioms Receiver.quarter_energy_ratio
#print axioms Receiver.bracket_upper
#print axioms Receiver.bracket_lower_pos
#print axioms Receiver.advective_exponent_gt_half_iff
#print axioms Receiver.advective_exponent_lt_one
#print axioms Receiver.finite_energy_iff
#print axioms Receiver.window
#print axioms Receiver.window_quarter
#print axioms Receiver.sphere_average_rotational
#print axioms Receiver.weighted_projection
#print axioms Receiver.rigid_rotation_saturates
#print axioms Receiver.cubic_remainder_constant
